### ISSUE TITLE
API specifications does not follow to Italian interoperability rules

### ISSUE THREAD

**Issue by ioggstream** [immuni-app/immuni-documentation#32]
## I expect

API specs to conform Interoperability rules.

## Instead

- [ ] they use Swagger 2.0 instead of OpenAPI >= 3.0. See #33 
- [ ] error schema does not conform RFC7807 Problem+Json
- [x] detail cache usage #36 
- [x] prefix header with an unique label (Eg. `Immuni` #38)  Fixed: #78 

## Note

You can use the [online checker](https://teamdigitale.github.io/api-oas-checker/) for further hints.

**Comment by immuniopensource** [comment]
Thank you @ioggstream for your contributions! We are currently reviewing your PRs and we will provide you detailed feedback as soon as possible.

**Comment by ioggstream** [comment]
Great, feel free to contact me directly if you need.

**Comment by ocardia** [comment]
Hey @ioggstream,

First of all, our apologies for not replying in the last two months, and thanks for taking the time for pointing this out.

Let’s go over the remaining bullet points one by one.

> they use Swagger 2.0 instead of OpenAPI >= 3.0. See #33

Thanks for opening this PR, it is much appreciated. Merging it caused closing this issue before our reply.

> error schema does not conform RFC7807 Problem+Json

This is definitely an enhancement, and thanks for pointing it out. Yet, given the current status of the project and the fact the current implementation does not inhibit the correct functionality, we won’t change it.

To support this decision, please consider that this change affects both the backend services and the clients, changing their interfaces. In turn, this would require swiftly handling backwards compatibility matters for old versions of the client—an effort not worth the benefits, at the moment. We may reconsider this later.

> detail cache usage #36

This point will be handled in the specific Issue #36.

All in all, this issue should now remain closed.

**Comment by ioggstream** [comment]
@ocardia thanks for the summary.

for this release it is fine to avoid changes to the error schema as long as the emergency persists.
